# 1) Pass assets under /posts/:slug/ through normally
[[redirects]]
  from   = "/posts/:slug/:file.:ext"
  to     = "/posts/:slug/:file.:ext"
  status = 200
  force  = true

# 2) Rewrite pretty URLs → your loader
[[redirects]]
  from   = "/posts/:slug"
  to     = "/post.html?postId=:slug"
  status = 200
  force  = true

[[redirects]]
  from   = "/posts/:slug/*"
  to     = "/post.html?postId=:slug"
  status = 200
  force  = true
