# ───────────────────────────────────────────────────
# 1) Pass-through real assets (images, CSS, JS) under /posts/:slug/
[[redirects]]
  from   = "/posts/:slug/:file.:ext"
  to     = "/posts/:slug/:file.:ext"
  status = 200
  force  = true

# ───────────────────────────────────────────────────
# 2) Redirect old query-string URL → pretty URL
[[redirects]]
  from       = "/post"
  to         = "/posts/:slug/"
  status     = 301
  force      = true
  conditions = { Query = { postId = ":slug" } }

# ───────────────────────────────────────────────────
# 3) Rewrite pretty → your SPA loader
[[redirects]]
  from   = "/posts/:slug"
  to     = "/post.html?postId=:slug"
  status = 200
  force  = true

[[redirects]]
  from   = "/posts/:slug/*"
  to     = "/post.html?postId=:slug"
  status = 200
  force  = true
