# 1) Pass‐through real assets under /posts/:slug/ 
[[redirects]]
  from   = "/posts/:slug/:file.:ext"
  to     = "/posts/:slug/:file.:ext"
  status = 200
  force  = true

# 2) 301 from old query → pretty URL, but strip the query by adding '?'
[[redirects]]
  from       = "/post"
  to         = "/posts/:slug/?"           # <-- the trailing '?' drops ?postId=…
  status     = 301
  force      = true
  query      = { postId = ":slug" }

# 3) Internally rewrite pretty → SPA loader
[[redirects]]
  from   = "/posts/:slug"
  to     = "/post.html?postId=:slug"
  status = 200
  force  = true

[[redirects]]
  from   = "/posts/:slug/*"
  to     = "/post.html?postId=:slug"
  status = 200
  force  = true
